-- Insert 15 sample courses (using DEFAULT values for id and timestamps)
INSERT INTO course (title, description, topics, price, duration_hours, difficulty_level, published) VALUES
('Introduction to Programming', 'Learn basic programming concepts with Python',
 '["Python", "Variables", "Loops", "Functions"]', 49.99, 20, 'BEGINNER', true),
('Web Development Fundamentals', 'HTML, CSS and JavaScript basics',
 '["HTML", "CSS", "JavaScript", "Responsive Design"]', 59.99, 30, 'BEGINNER', true),
('Git and GitHub for Beginners', 'Version control essentials',
 '["Git", "GitHub", "Version Control", "Collaboration"]', 29.99, 10, 'BEGINNER', true),
('Spring Boot Essentials', 'Build REST APIs with Spring Boot',
 '["Java", "Spring Boot", "REST API", "JPA"]', 79.99, 40, 'INTERMEDIATE', true),
('React.js Deep Dive', 'Master React hooks and context API',
 '["React", "Hooks", "Context API", "Components"]', 69.99, 35, 'INTERMEDIATE', true),
('Docker for Developers', 'Containerize your applications',
 '["Docker", "Containers", "Dockerfile", "Docker Compose"]', 59.99, 25, 'INTERMEDIATE', true),
('Microservices Architecture', 'Design scalable microservices systems',
 '["Microservices", "Spring Cloud", "Kubernetes", "Distributed Systems"]', 99.99, 50, 'ADVANCED', true),
('Machine Learning with Python', 'Introduction to ML algorithms',
 '["Python", "TensorFlow", "Neural Networks", "Scikit-learn"]', 89.99, 45, 'ADVANCED', true),
('AWS Certified Solutions Architect', 'Prepare for AWS certification',
 '["AWS", "Cloud Computing", "EC2", "S3", "Lambda"]', 119.99, 60, 'ADVANCED', true),
('Mobile App Development with Flutter', 'Build cross-platform mobile apps',
 '["Flutter", "Dart", "Mobile Development", "UI/UX"]', 74.99, 40, 'INTERMEDIATE', true),
('GraphQL API Development', 'Modern API development with GraphQL',
 '["GraphQL", "API", "Node.js", "Apollo"]', 64.99, 30, 'INTERMEDIATE', true),
('Cybersecurity Fundamentals', 'Essential security concepts for developers',
 '["Security", "OWASP", "Encryption", "Authentication"]', 84.99, 35, 'INTERMEDIATE', true),
('Data Structures and Algorithms', 'Master fundamental CS concepts',
 '["Algorithms", "Data Structures", "Big-O", "Problem Solving"]', 89.99, 50, 'ADVANCED', true),
('DevOps CI/CD Pipeline', 'Automate your development workflow',
 '["Jenkins", "GitHub Actions", "CI/CD", "Automation"]', 79.99, 45, 'ADVANCED', true),
('Blockchain Basics', 'Introduction to blockchain technology',
 '["Blockchain", "Smart Contracts", "Ethereum", "Solidity"]', 94.99, 40, 'ADVANCED', true);