server:
  port: 9090

spring:
  application:
    name: course-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/course-db}
    username: ${DB_USER:course}
    password: ${DB_PASSWORD:course}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations:
      - classpath:db/migration
    baseline-on-migrate: true